### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by lazyharpseal5492** [mountain658/mountain658.github.io#16]
chat doesnt exist(yet) >:(((
solution: i have a brand new one made, i just need you guys to add it

**Comment by shotgunshelly** [comment]
What server is it running through and would it require a subscription like replit does?

**Comment by lazyharpseal5492** [comment]
self hosted through my own server, already discussed it with mountain

**Comment by shotgunshelly** [comment]
Well i will talk to him it may be up as early as monday

**Comment by lazyharpseal5492** [comment]
resolved, got finished and working, just need you guys to replace the old one with the new one
