### ISSUE TITLE
Moto X3m Is just a white screen

### ISSUE THREAD

**Issue by super-15** [mountain658/mountain658.github.io#7]
I downloaded the Moto X3M source code from https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fmountain658%2Fmountain658.github.io%2Ftree%2Fmain%2Fg%2Fmoto-x3m and I extracted it and ran the index.html. It just shows a white screen.

**Comment by mountain658** [comment]
It needs to be served over HTTP (it needs to be on a website) because most computers block some internet features when running over a file. Github lets you have one free website, here's a site about it: [https://pages.github.com](https://pages.github.com). Good luck!
